/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_strangersprings_zpr_client_service_calc_Calculator */

#ifndef _Included_com_strangersprings_zpr_client_service_calc_Calculator
#define _Included_com_strangersprings_zpr_client_service_calc_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_strangersprings_zpr_client_service_calc_Calculator
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_strangersprings_zpr_client_service_calc_Calculator_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
