version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: dev_mysql
    ports:
      - 3306:3306
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zpr
      MYSQL_PASSWORD: user