version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: dev_mysql
    ports:
      - 3306:3306
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zpr
      MYSQL_PASSWORD: user
    networks:
      - backend

  currency-api:
    image: currency-api:dss
    build:
    context: ./currency-api
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    restart: always
    environment:
      SERVER_PORT: 8082
    networks:
      - api

  client:
    image: client:dss
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/zpr?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      APP_APIURL: http://currency-api:8082
      SERVER_PORT: 8080
    depends_on:
      - mysql
      - currency-api
    networks:
      - api
      - backend
      - frontend

  web:
    image: web:dss
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - 3000:3000
    restart: always
    environment:
      - NODE_ENV=development
    depends_on:
      - client
    networks:
      - frontend

## Networks to be created to facilitate communication between containers
networks:
  backend:
  api:
  frontend: