/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_strangersprings_zpr_client_process_service_calc_Calculator */

#ifndef _Included_com_strangersprings_zpr_client_process_service_calc_Calculator
#define _Included_com_strangersprings_zpr_client_process_service_calc_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_strangersprings_zpr_client_process_service_calc_Calculator
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_strangersprings_zpr_client_process_service_calc_Calculator_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_strangersprings_zpr_client_process_service_calc_Calculator
 * Method:    updateAggregation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_strangersprings_zpr_client_process_service_calc_Calculator_updateAggregation
  (JNIEnv *, jobject);

/*
 * Class:     com_strangersprings_zpr_client_process_service_calc_Calculator
 * Method:    updateIndex
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_strangersprings_zpr_client_process_service_calc_Calculator_updateIndex
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
