/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_strangersprings_zpr_client_service_calc_Calculator */

#ifndef _Included_com_strangersprings_zpr_client_service_calc_Calculator
#define _Included_com_strangersprings_zpr_client_service_calc_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_strangersprings_zpr_client_service_calc_Calculator
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_strangersprings_zpr_client_service_calc_Calculator_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_strangersprings_zpr_client_service_calc_Calculator
 * Method:    calculate
 * Signature: (Lcom/strangersprings/zpr/client/service/calc/CurrencyDTO;)Lcom/strangersprings/zpr/client/service/calc/CurrencyIndicator;
 */
JNIEXPORT jobject JNICALL Java_com_strangersprings_zpr_client_service_calc_Calculator_calculate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_strangersprings_zpr_client_service_calc_Calculator
 * Method:    bitcoinAverage
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_strangersprings_zpr_client_service_calc_Calculator_bitcoinAverage
  (JNIEnv *, jobject);

/*
 * Class:     com_strangersprings_zpr_client_service_calc_Calculator
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_strangersprings_zpr_client_service_calc_Calculator_init
  (JNIEnv *, jobject);

/*
 * Class:     com_strangersprings_zpr_client_service_calc_Calculator
 * Method:    insertBitcoin
 * Signature: (Lcom/strangersprings/zpr/client/service/calc/CurrencyDTO;)V
 */
JNIEXPORT void JNICALL Java_com_strangersprings_zpr_client_service_calc_Calculator_insertBitcoin
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
