/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_strangersprings_zpr_client_service_calc_Calculator */

#ifndef _Included_com_strangersprings_zpr_client_service_calc_Calculator
#define _Included_com_strangersprings_zpr_client_service_calc_Calculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_strangersprings_zpr_client_service_calc_Calculator
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_strangersprings_zpr_client_service_calc_Calculator_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_strangersprings_zpr_client_service_calc_Calculator
 * Method:    init
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_strangersprings_zpr_client_service_calc_Calculator_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_strangersprings_zpr_client_service_calc_Calculator
 * Method:    calculateAll
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_strangersprings_zpr_client_service_calc_Calculator_calculateAll
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
